# generated by datamodel-codegen:
#   filename:  _all.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, PositiveInt, conint, constr


class LockInEvents(BaseModel):
    """
    All LockIn v1 event types as JSON Schema definitions.
    """


class Source(StrEnum):
    web = "web"
    mcp = "mcp"
    api = "api"
    agent = "agent"


class Source1(StrEnum):
    keyboard = "keyboard"
    click = "click"
    voice = "voice"
    mcp = "mcp"


class Priority(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: UUID
    title: constr(min_length=1, max_length=500)
    source: Source1
    due_date: AwareDatetime | None = None
    priority: Priority | None = None
    estimated_minutes: PositiveInt | None = None


class TaskCreated(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["task.created"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source
    payload: Payload


class Source2(StrEnum):
    web = "web"
    mcp = "mcp"
    api = "api"
    agent = "agent"


class Payload1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: UUID
    scheduled_start: AwareDatetime
    scheduled_end: AwareDatetime
    explanation_id: UUID


class TaskScheduled(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["task.scheduled"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload1


class Payload2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: UUID
    schedule_id: UUID


class TaskAccepted(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["task.accepted"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload2


class Reason(StrEnum):
    wrong_time = "wrong_time"
    wrong_duration = "wrong_duration"
    wrong_priority = "wrong_priority"
    other = "other"


class Payload3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: UUID
    schedule_id: UUID
    reason: Reason | None = None
    free_text: constr(max_length=2000) | None = None


class TaskRejected(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["task.rejected"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload3


class Payload4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: UUID
    changes: dict[str, Any]


class TaskModified(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["task.modified"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload4


class Payload5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: UUID
    completed_at: AwareDatetime
    actual_minutes: conint(ge=0) | None = None


class TaskCompleted(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["task.completed"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload5


class Mood(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5


class Context(StrEnum):
    morning = "morning"
    post_lunch = "post_lunch"
    mid_afternoon = "mid_afternoon"
    evening = "evening"


class Payload6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mood: Mood
    context: Context | None = None


class MoodLogged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["mood.logged"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload6


class Energy(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5


class Payload7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    energy: Energy
    context: Context | None = None


class EnergyLogged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["energy.logged"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload7


class Factor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    weight: float
    value: str | float | bool


class Payload8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    explanation_id: UUID
    task_id: UUID
    factors: list[Factor]
    model_version: str
    rendered_text: constr(max_length=4000)


class ScheduleExplained(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    event_type: Literal["schedule.explained"]
    event_version: Literal[1]
    user_id: UUID
    tenant_id: UUID | None
    occurred_at: AwareDatetime
    client_idempotency_key: constr(min_length=1, max_length=128) | None
    source: Source2
    payload: Payload8
